language: go

stages:
  - test
  - coverage

go:
  - 1.15.x

env: GO111MODULE=on

before_install:
  - go get -u github.com/kyoh86/richgo

matrix:
  include:
    - stage: test
      go: 1.15.x
      script: make test
    - stage: coverage
      go: 1.15.x
      script: make codecov
      after_success: bash <(curl -s https://codecov.io/bash)
